services:
  redis-node-1:
    image: redis:8-alpine
    container_name: redis-node-1
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./docker/cluster/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7001", "--cluster-announce-ip", "redis-node-1", "--cluster-announce-port", "7001", "--cluster-announce-bus-port", "17001"]

  redis-node-2:
    image: redis:8-alpine
    container_name: redis-node-2
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./docker/cluster/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7002", "--cluster-announce-ip", "redis-node-2", "--cluster-announce-port", "7002", "--cluster-announce-bus-port", "17002"]

  redis-node-3:
    image: redis:8-alpine
    container_name: redis-node-3
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./docker/cluster/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7003", "--cluster-announce-ip", "redis-node-3", "--cluster-announce-port", "7003", "--cluster-announce-bus-port", "17003"]

  redis-node-4:
    image: redis:8-alpine
    container_name: redis-node-4
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - ./docker/cluster/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7004", "--cluster-announce-ip", "redis-node-4", "--cluster-announce-port", "7004", "--cluster-announce-bus-port", "17004"]

  redis-node-5:
    image: redis:8-alpine
    container_name: redis-node-5
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - ./docker/cluster/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7005", "--cluster-announce-ip", "redis-node-5", "--cluster-announce-port", "7005", "--cluster-announce-bus-port", "17005"]

  redis-node-6:
    image: redis:8-alpine
    container_name: redis-node-6
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
      - ./docker/cluster/redis-cluster.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7006", "--cluster-announce-ip", "redis-node-6", "--cluster-announce-port", "7006", "--cluster-announce-bus-port", "17006"]

  redis-cluster-init:
    image: redis:8-alpine
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    command: >
      sh -c "sleep 5 &&
      redis-cli --cluster create
      redis-node-1:7001 redis-node-2:7002 redis-node-3:7003
      redis-node-4:7004 redis-node-5:7005 redis-node-6:7006
      --cluster-replicas 1 --cluster-yes"
